# Generated by Django 4.2.2 on 2023-06-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_product1_alter_cartitem_product_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(default=None, null=True, upload_to='products/img')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='products/img'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.item'),
        ),
    ]
