# Generated by Django 4.2.2 on 2023-06-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_item_cartitem_image_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='products/img2'),
        ),
    ]
