# Generated by Django 4.1.7 on 2023-08-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_alter_cartitem_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product1',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(upload_to='products/img2'),
        ),
    ]
